steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', ${_IMAGE_NAME}, '.']
substitutions:
    _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/test-image'
options:
    dynamic_substitutions: true


